services:
  frontend:
    image: ghcr.io/narek-hayrapetyan1/frontend:latest
    container_name: nginx
    ports:
      - 3000:3000
    networks:
      - frontend

  backend:
    image: ghcr.io/narek-hayrapetyan1/frontend:latest
    container_name: fastapi
    secrets:
      - pg_password
    networks:
      - backend
      - frontend
    ports:
      - 8000:8000
    env_file:
      - backend/.env
    depends_on:
      - db


  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: my_user
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - pg_password
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

secrets:
  pg_password:
    file: pg_password.txt