name: deploy services

on:
  push:
    branches:
      - main


jobs:
  service_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
        continue-on-error: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: backend/
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/backend:latest

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: frontend/
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/frontend:latest
